name: Centralized Windows EC2 Validation

on:
  workflow_dispatch:
    inputs:
      region:
        description: AWS region
        required: true
        default: us-west-2
      server_name:
        description: EC2 Name tag
        required: false
        default: ""
      instance_id:
        description: EC2 instance id
        required: false
        default: ""
      expected_hostname:
        description: Expected Windows hostname
        required: false
        default: ""
      expected_timezone:
        description: Expected Windows timezone
        required: true
        default: "Mountain Standard Time"
      expected_domain:
        description: Expected AD domain
        required: false
        default: ""
      dns_name_to_resolve:
        description: Optional DNS name
        required: false
        default: ""
      required_services_csv:
        description: Required services
        required: true
        default: "AmazonSSMAgent,AmazonCloudWatchAgent,Amsp,scaleft-server-tools"
      fail_on_validation_issues:
        description: Fail if any server validation fails
        required: true
        default: "false"

jobs:
  validate:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      DOCUMENT_NAME: Centralized-Windows-EC2-Validation

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.region }}
          role-to-assume: arn:aws:iam::345362761155:role/OIDCRoleForGitHubActions

      - name: Resolve target instance
        shell: bash
        env:
          REGION: ${{ inputs.region }}
          SERVER_NAME: ${{ inputs.server_name }}
          INSTANCE_ID: ${{ inputs.instance_id }}
        run: |
          # Code Generated by Sidekick is for learning and experimentation purposes only.
          set -euo pipefail

          if [ -n "$INSTANCE_ID" ]; then
            TARGET_INSTANCE_ID="$INSTANCE_ID"
          else
            IDS="$(aws ec2 describe-instances \
              --region "$REGION" \
              --filters "Name=tag:Name,Values=$SERVER_NAME" "Name=instance-state-name,Values=running" \
              --query "Reservations[].Instances[].InstanceId" \
              --output text)"

            if [ -z "$IDS" ] || [ "$IDS" = "None" ]; then
              echo "No running instance found for server_name=$SERVER_NAME" >&2
              exit 1
            fi

            set -- $IDS
            if [ "$#" -gt 1 ]; then
              echo "Multiple running instances found for server_name=$SERVER_NAME. Use instance_id." >&2
              exit 1
            fi

            TARGET_INSTANCE_ID="$1"
          fi

          echo "TARGET_INSTANCE_ID=$TARGET_INSTANCE_ID" >> "$GITHUB_ENV"
          echo "Target instance: $TARGET_INSTANCE_ID"

      - name: Run Windows validation via SSM document
        shell: bash
        env:
          REGION: ${{ inputs.region }}
          EXPECTED_HOSTNAME: ${{ inputs.expected_hostname }}
          EXPECTED_TIMEZONE: ${{ inputs.expected_timezone }}
          EXPECTED_DOMAIN: ${{ inputs.expected_domain }}
          DNS_NAME_TO_RESOLVE: ${{ inputs.dns_name_to_resolve }}
          REQUIRED_SERVICES_CSV: ${{ inputs.required_services_csv }}
          FAIL_ON_VALIDATION_ISSUES: ${{ inputs.fail_on_validation_issues }}
        run: |
          # Code Generated by Sidekick is for learning and experimentation purposes only.
          set -euo pipefail

          python3 - <<'PY'
          import json, os
          params = {
              "ExpectedHostname": [os.environ.get("EXPECTED_HOSTNAME", "")],
              "ExpectedTimezone": [os.environ.get("EXPECTED_TIMEZONE", "")],
              "ExpectedDomain": [os.environ.get("EXPECTED_DOMAIN", "")],
              "DnsNameToResolve": [os.environ.get("DNS_NAME_TO_RESOLVE", "")],
              "RequiredServicesCsv": [os.environ.get("REQUIRED_SERVICES_CSV", "")],
              "FailOnValidationIssues": [os.environ.get("FAIL_ON_VALIDATION_ISSUES", "false")]
          }
          with open("params.json", "w", encoding="utf-8") as f:
              json.dump(params, f)
          PY

          COMMAND_ID="$(aws ssm send-command \
            --region "$REGION" \
            --document-name "$DOCUMENT_NAME" \
            --instance-ids "$TARGET_INSTANCE_ID" \
            --parameters file://params.json \
            --query "Command.CommandId" \
            --output text)"

          echo "SSM Command ID: $COMMAND_ID"

          FINAL_STATUS=""
          for _ in $(seq 1 24); do
            STATUS="$(aws ssm get-command-invocation \
              --region "$REGION" \
              --command-id "$COMMAND_ID" \
              --instance-id "$TARGET_INSTANCE_ID" \
              --query "Status" \
              --output text 2>/dev/null || true)"

            case "$STATUS" in
              Success|Failed|TimedOut|Cancelled|Cancelling)
                FINAL_STATUS="$STATUS"
                break
                ;;
              *)
                sleep 5
                ;;
            esac
          done

          [ -n "$FINAL_STATUS" ] || FINAL_STATUS="$(aws ssm get-command-invocation \
            --region "$REGION" \
            --command-id "$COMMAND_ID" \
            --instance-id "$TARGET_INSTANCE_ID" \
            --query "Status" \
            --output text)"

          STDOUT_CONTENT="$(aws ssm get-command-invocation \
            --region "$REGION" \
            --command-id "$COMMAND_ID" \
            --instance-id "$TARGET_INSTANCE_ID" \
            --query "StandardOutputContent" \
            --output text)"

          STDERR_CONTENT="$(aws ssm get-command-invocation \
            --region "$REGION" \
            --command-id "$COMMAND_ID" \
            --instance-id "$TARGET_INSTANCE_ID" \
            --query "StandardErrorContent" \
            --output text)"

          echo "$STDOUT_CONTENT"

          if [ -n "$STDERR_CONTENT" ] && [ "$STDERR_CONTENT" != "None" ]; then
            echo "$STDERR_CONTENT" >&2
          fi

          if [ "$FINAL_STATUS" != "Success" ]; then
            echo "SSM validation failed with status: $FINAL_STATUS" >&2
            exit 1
          fi
