#!/usr/bin/env bash
set -euo pipefail

REGION="${REGION:-us-west-2}"
SERVER_NAME="${SERVER_NAME:-}"
INSTANCE_ID="${INSTANCE_ID:-}"
EXPECTED_TIMEZONE="${EXPECTED_TIMEZONE:-Mountain Standard Time}"
EXPECTED_DOMAIN="${EXPECTED_DOMAIN:-}"
DNS_NAME_TO_RESOLVE="${DNS_NAME_TO_RESOLVE:-}"
REQUIRED_SERVICES_CSV="${REQUIRED_SERVICES_CSV:-AmazonSSMAgent,AmazonCloudWatchAgent,Amsp,scaleft-server-tools}"
FAIL_ON_VALIDATION_ISSUES="${FAIL_ON_VALIDATION_ISSUES:-false}"

if [[ -z "$INSTANCE_ID" && -z "$SERVER_NAME" ]]; then
  echo "ERROR: set INSTANCE_ID or SERVER_NAME"
  exit 1
fi

for cmd in aws python3; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "ERROR: required command not found: $cmd"
    exit 1
  fi
done

json_query() {
  python3 - "$@" <<'PY'
# Code Generated by Sidekick is for learning and experimentation purposes only.
import json,sys
data=json.load(sys.stdin)
expr=sys.argv[1]

def first_name_tag(tags):
    if not tags:
        return "(No Name tag)"
    for t in tags:
        if t.get("Key") == "Name":
            return t.get("Value") or "(No Name tag)"
    return "(No Name tag)"

if expr == "pick_instance":
    target_id = sys.argv[2]
    target_name = sys.argv[3].lower()
    picked = None
    for r in data.get("Reservations", []):
        for i in r.get("Instances", []):
            if target_id and i.get("InstanceId") == target_id:
                picked = i
                break
            if target_name:
                name = first_name_tag(i.get("Tags", []))
                if name.lower() == target_name:
                    picked = i
                    break
        if picked:
            break
    if not picked:
        sys.exit(2)
    print(json.dumps(picked))
elif expr == "instance_summary":
    name = first_name_tag(data.get("Tags", []))
    primary_ip = ""
    secondary_ips = []
    nis = data.get("NetworkInterfaces", [])
    if nis:
        ni0 = nis[0]
        primary_ip = ni0.get("PrivateIpAddress", "")
        for pip in ni0.get("PrivateIpAddresses", []):
            if not pip.get("Primary", False) and pip.get("PrivateIpAddress"):
                secondary_ips.append(pip["PrivateIpAddress"])
    out = {
        "ServerName": name,
        "InstanceId": data.get("InstanceId",""),
        "VpcId": data.get("VpcId",""),
        "SubnetId": data.get("SubnetId",""),
        "InstanceType": data.get("InstanceType",""),
        "EbsCount": len(data.get("BlockDeviceMappings", [])),
        "PrimaryIP": primary_ip,
        "SecondaryIPs": ",".join(secondary_ips) if secondary_ips else "None",
        "SecurityGroupNames": ",".join([x.get("GroupName","") for x in data.get("SecurityGroups", []) if x.get("GroupName")]),
        "SecurityGroupIds": ",".join([x.get("GroupId","") for x in data.get("SecurityGroups", []) if x.get("GroupId")]),
        "VolumeIds": [x.get("Ebs",{}).get("VolumeId","") for x in data.get("BlockDeviceMappings", []) if x.get("Ebs",{}).get("VolumeId")],
        "BlockDeviceMappings": data.get("BlockDeviceMappings", []),
        "Tags": data.get("Tags", [])
    }
    print(json.dumps(out))
elif expr == "instance_type_summary":
    it = data["InstanceTypes"][0]
    out = {
        "vCPUs": it.get("VCpuInfo",{}).get("DefaultVCpus",""),
        "RAMGiB": round((it.get("MemoryInfo",{}).get("SizeInMiB",0))/1024, 2)
    }
    print(json.dumps(out))
elif expr == "instance_health":
    sts = data.get("InstanceStatuses", [])
    if not sts:
        print(json.dumps({"SystemHealth":"N/A","InstanceHealth":"N/A"}))
    else:
        s = sts[0]
        print(json.dumps({
            "SystemHealth": s.get("SystemStatus",{}).get("Status","N/A"),
            "InstanceHealth": s.get("InstanceStatus",{}).get("Status","N/A")
        }))
elif expr == "tag_name":
    tags = data.get("Tags", [])
    print(tags[0].get("Value","(No Name tag)") if tags else "(No Name tag)")
elif expr == "ebs_details":
    block_map = json.loads(sys.argv[2])
    vols = {v["VolumeId"]: v for v in data.get("Volumes", [])}
    out = []
    for b in block_map:
        vid = b.get("Ebs",{}).get("VolumeId","")
        v = vols.get(vid,{})
        out.append({
            "DeviceName": b.get("DeviceName",""),
            "VolumeId": vid,
            "Type": v.get("VolumeType","N/A"),
            "SizeGB": v.get("Size","N/A"),
            "IOPS": v.get("Iops","N/A"),
            "Encrypted": v.get("Encrypted","N/A")
        })
    print(json.dumps(out))
else:
    sys.exit(3)
PY
}

echo "Resolving target instance..."
DESCRIBE_JSON="$(aws ec2 describe-instances --region "$REGION" --output json)"
INSTANCE_JSON="$(printf '%s' "$DESCRIBE_JSON" | json_query pick_instance "${INSTANCE_ID:-}" "${SERVER_NAME:-}")" || {
  echo "ERROR: instance not found"
  exit 1
}

SUMMARY_JSON="$(printf '%s' "$INSTANCE_JSON" | json_query instance_summary)"
INSTANCE_ID="$(python3 -c 'import json,sys; print(json.load(sys.stdin)["InstanceId"])' <<< "$SUMMARY_JSON")"
SERVER_NAME="$(python3 -c 'import json,sys; print(json.load(sys.stdin)["ServerName"])' <<< "$SUMMARY_JSON")"
VPC_ID="$(python3 -c 'import json,sys; print(json.load(sys.stdin)["VpcId"])' <<< "$SUMMARY_JSON")"
SUBNET_ID="$(python3 -c 'import json,sys; print(json.load(sys.stdin)["SubnetId"])' <<< "$SUMMARY_JSON")"
INSTANCE_TYPE="$(python3 -c 'import json,sys; print(json.load(sys.stdin)["InstanceType"])' <<< "$SUMMARY_JSON")"
EBS_COUNT="$(python3 -c 'import json,sys; print(json.load(sys.stdin)["EbsCount"])' <<< "$SUMMARY_JSON")"
PRIMARY_IP="$(python3 -c 'import json,sys; print(json.load(sys.stdin)["PrimaryIP"])' <<< "$SUMMARY_JSON")"
SECONDARY_IPS="$(python3 -c 'import json,sys; print(json.load(sys.stdin)["SecondaryIPs"])' <<< "$SUMMARY_JSON")"
SG_NAMES="$(python3 -c 'import json,sys; print(json.load(sys.stdin)["SecurityGroupNames"])' <<< "$SUMMARY_JSON")"
SG_IDS="$(python3 -c 'import json,sys; print(json.load(sys.stdin)["SecurityGroupIds"])' <<< "$SUMMARY_JSON")"
VOLUME_IDS_CSV="$(python3 -c 'import json,sys; print(" ".join(json.load(sys.stdin)["VolumeIds"]))' <<< "$SUMMARY_JSON")"
BLOCK_DEVICE_MAPPINGS_JSON="$(python3 -c 'import json,sys; print(json.dumps(json.load(sys.stdin)["BlockDeviceMappings"]))' <<< "$SUMMARY_JSON")"
TAGS_JSON="$(python3 -c 'import json,sys; print(json.dumps(json.load(sys.stdin)["Tags"]))' <<< "$SUMMARY_JSON")"

ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"
VPC_NAME="$(aws ec2 describe-tags --region "$REGION" --filters "Name=resource-id,Values=$VPC_ID" "Name=key,Values=Name" --output json | json_query tag_name)"
SUBNET_NAME="$(aws ec2 describe-tags --region "$REGION" --filters "Name=resource-id,Values=$SUBNET_ID" "Name=key,Values=Name" --output json | json_query tag_name)"

ITYPE_JSON="$(aws ec2 describe-instance-types --region "$REGION" --instance-types "$INSTANCE_TYPE" --output json)"
ITYPE_SUMMARY="$(printf '%s' "$ITYPE_JSON" | json_query instance_type_summary)"
VCPUS="$(python3 -c 'import json,sys; print(json.load(sys.stdin)["vCPUs"])' <<< "$ITYPE_SUMMARY")"
RAM_GIB="$(python3 -c 'import json,sys; print(json.load(sys.stdin)["RAMGiB"])' <<< "$ITYPE_SUMMARY")"

HEALTH_JSON="$(aws ec2 describe-instance-status --region "$REGION" --instance-ids "$INSTANCE_ID" --output json)"
HEALTH_SUMMARY="$(printf '%s' "$HEALTH_JSON" | json_query instance_health)"
SYSTEM_HEALTH="$(python3 -c 'import json,sys; print(json.load(sys.stdin)["SystemHealth"])' <<< "$HEALTH_SUMMARY")"
INSTANCE_HEALTH="$(python3 -c 'import json,sys; print(json.load(sys.stdin)["InstanceHealth"])' <<< "$HEALTH_SUMMARY")"

EBS_DETAILS_JSON="[]"
if [[ -n "$VOLUME_IDS_CSV" ]]; then
  VOLS_JSON="$(aws ec2 describe-volumes --region "$REGION" --volume-ids $VOLUME_IDS_CSV --output json)"
  EBS_DETAILS_JSON="$(printf '%s' "$VOLS_JSON" | json_query ebs_details "$BLOCK_DEVICE_MAPPINGS_JSON")"
fi

cat > server-validation.ps1 <<'POWERSHELL'
# Code Generated by Sidekick is for learning and experimentation purposes only.
param(
    [string]$ExpectedTimeZone = "Mountain Standard Time",
    [string]$ExpectedDomain = "",
    [string]$DnsNameToResolve = "",
    [string]$RequiredServicesCsv = "AmazonSSMAgent,AmazonCloudWatchAgent,Amsp,scaleft-server-tools",
    [string]$FailOnValidationIssues = "false"
)

$ErrorActionPreference = "Stop"
$results = @()

function Add-ValidationResult {
    param([string]$Step,[string]$Item,[string]$Status,[string]$Details)
    $script:results += [PSCustomObject]@{
        Timestamp = (Get-Date).ToString("s")
        Step      = $Step
        Item      = $Item
        Status    = $Status
        Details   = $Details
    }
    Write-Output ("[{0}] {1} | {2} | {3}" -f $Status, $Step, $Item, $Details)
}

function Safe-ResolveDns {
    param([string]$Name)
    try {
        $records = Resolve-DnsName -Name $Name -Type A -ErrorAction Stop
        return @($records | Where-Object { $_.IPAddress } | Select-Object -ExpandProperty IPAddress)
    }
    catch {
        return @()
    }
}

try {
    $RequiredServices = @($RequiredServicesCsv -split '\s*,\s*' | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })
    $ShouldFail = $FailOnValidationIssues.Trim().ToLower() -eq "true"

    $computer = Get-CimInstance Win32_ComputerSystem
    $os = Get-CimInstance Win32_OperatingSystem

    try {
        $fqdn = ([System.Net.Dns]::GetHostEntry($env:COMPUTERNAME)).HostName
    }
    catch {
        if ($computer.PartOfDomain -and $computer.Domain) {
            $fqdn = "$($computer.Name).$($computer.Domain)"
        }
        else {
            $fqdn = $computer.Name
        }
    }

    if ([string]::IsNullOrWhiteSpace($DnsNameToResolve)) {
        $DnsNameToResolve = $fqdn
    }

    Add-ValidationResult -Step "Validate Server Identity" -Item $env:COMPUTERNAME -Status "PASS" -Details "ComputerName=$($computer.Name); Domain=$($computer.Domain); FQDN=$fqdn"
    Add-ValidationResult -Step "Validate Operating System" -Item "Operating System" -Status "PASS" -Details "OSName=$($os.Caption); OSVersion=$($os.Version); BuildNumber=$($os.BuildNumber)"

    try {
        $volumes = Get-Volume | Where-Object { $_.DriveLetter }
        if (-not $volumes) {
            Add-ValidationResult -Step "Validate Volume Configuration" -Item "Volumes" -Status "FAIL" -Details "No mounted volumes with drive letters found"
        }
        else {
            $badVolumes = @($volumes | Where-Object { $_.HealthStatus -ne "Healthy" })
            $volumeDetails = ($volumes | ForEach-Object {
                "DriveLetter=$($_.DriveLetter); FileSystem=$($_.FileSystem); SizeRemainingGB=$([math]::Round($_.SizeRemaining / 1GB, 2)); SizeGB=$([math]::Round($_.Size / 1GB, 2)); HealthStatus=$($_.HealthStatus)"
            }) -join " | "
            Add-ValidationResult -Step "Validate Volume Configuration" -Item "Volumes" -Status $(if ($badVolumes.Count -gt 0) { "FAIL" } else { "PASS" }) -Details $volumeDetails
        }
    }
    catch {
        Add-ValidationResult -Step "Validate Volume Configuration" -Item "Volumes" -Status "FAIL" -Details $_.Exception.Message
    }

    foreach ($svc in $RequiredServices) {
        try {
            $service = Get-Service -Name $svc -ErrorAction SilentlyContinue
            if ($null -eq $service) {
                Add-ValidationResult -Step "Validate Required Windows Services" -Item $svc -Status "FAIL" -Details "Service not found"
            }
            elseif ($service.Status -eq "Running") {
                Add-ValidationResult -Step "Validate Required Windows Services" -Item $svc -Status "PASS" -Details "ServiceStatus=$($service.Status)"
            }
            else {
                Add-ValidationResult -Step "Validate Required Windows Services" -Item $svc -Status "FAIL" -Details "ServiceStatus=$($service.Status)"
            }
        }
        catch {
            Add-ValidationResult -Step "Validate Required Windows Services" -Item $svc -Status "FAIL" -Details $_.Exception.Message
        }
    }

    try {
        if (-not $computer.PartOfDomain) {
            Add-ValidationResult -Step "Validate Domain Membership" -Item $env:COMPUTERNAME -Status "FAIL" -Details "Server is not joined to any domain"
        }
        elseif (-not [string]::IsNullOrWhiteSpace($ExpectedDomain) -and $computer.Domain -ne $ExpectedDomain) {
            Add-ValidationResult -Step "Validate Domain Membership" -Item $env:COMPUTERNAME -Status "FAIL" -Details "CurrentDomain=$($computer.Domain); ExpectedDomain=$ExpectedDomain"
        }
        else {
            Add-ValidationResult -Step "Validate Domain Membership" -Item $env:COMPUTERNAME -Status "PASS" -Details "CurrentDomain=$($computer.Domain)"
        }
    }
    catch {
        Add-ValidationResult -Step "Validate Domain Membership" -Item $env:COMPUTERNAME -Status "FAIL" -Details $_.Exception.Message
    }

    try {
        $tz = Get-TimeZone
        if ($tz.Id -eq $ExpectedTimeZone) {
            Add-ValidationResult -Step "Validate Timezone Configuration" -Item "Timezone" -Status "PASS" -Details "Current=$($tz.Id); Expected=$ExpectedTimeZone"
        }
        else {
            Add-ValidationResult -Step "Validate Timezone Configuration" -Item "Timezone" -Status "FAIL" -Details "Current=$($tz.Id); Expected=$ExpectedTimeZone"
        }
    }
    catch {
        Add-ValidationResult -Step "Validate Timezone Configuration" -Item "Timezone" -Status "FAIL" -Details $_.Exception.Message
    }

    try {
        $resolvedIps = Safe-ResolveDns -Name $DnsNameToResolve
        if ($resolvedIps.Count -gt 0) {
            Add-ValidationResult -Step "Validate DNS Resolution" -Item $DnsNameToResolve -Status "PASS" -Details ("ResolvedIPs=" + ($resolvedIps -join ", "))
        }
        else {
            Add-ValidationResult -Step "Validate DNS Resolution" -Item $DnsNameToResolve -Status "FAIL" -Details "No A record resolved"
        }
    }
    catch {
        Add-ValidationResult -Step "Validate DNS Resolution" -Item $DnsNameToResolve -Status "FAIL" -Details $_.Exception.Message
    }

    $passCount = ($results | Where-Object { $_.Status -eq "PASS" }).Count
    $failCount = ($results | Where-Object { $_.Status -eq "FAIL" }).Count

    Write-Output ""
    Write-Output "VALIDATION SUMMARY"
    Write-Output "ComputerName: $env:COMPUTERNAME"
    Write-Output "FQDN: $fqdn"
    Write-Output "TotalChecks: $($results.Count)"
    Write-Output "Passed: $passCount"
    Write-Output "Failed: $failCount"

    if ($ShouldFail -and $failCount -gt 0) { exit 2 }
    exit 0
}
catch {
    Write-Output ("[ERROR] Fatal Error | {0} | {1}" -f $env:COMPUTERNAME, $_.Exception.Message)
    exit 1
}
POWERSHELL

PARAMS_JSON="$(python3 <<PY
# Code Generated by Sidekick is for learning and experimentation purposes only.
import json
with open("server-validation.ps1","r",encoding="utf-8") as f:
    commands = f.read().splitlines()
print(json.dumps({
    "commands": commands,
    "executionTimeout": ["3600"],
    "ExpectedTimeZone": ["$EXPECTED_TIMEZONE"],
    "ExpectedDomain": ["$EXPECTED_DOMAIN"],
    "DnsNameToResolve": ["$DNS_NAME_TO_RESOLVE"],
    "RequiredServicesCsv": ["$REQUIRED_SERVICES_CSV"],
    "FailOnValidationIssues": ["$FAIL_ON_VALIDATION_ISSUES"]
}))
PY
)"

echo ""
echo "EC2 INSTANCE DETAILS"
echo "Server Name: $SERVER_NAME"
echo "Region: $REGION"
echo "Instance ID: $INSTANCE_ID"
echo "Account ID: $ACCOUNT_ID"
echo "VPC Name: $VPC_NAME"
echo "Subnet Name: $SUBNET_NAME"
echo "Primary IP: $PRIMARY_IP"
echo "EBS Cnt: $EBS_COUNT"
echo "Type: $INSTANCE_TYPE"
echo "vCPUs: $VCPUS"
echo "RAM(GB): $RAM_GIB"
echo "SG Names: $SG_NAMES"
echo "SG IDs: $SG_IDS"
echo "SysHealth: $SYSTEM_HEALTH"
echo "InstHealth: $INSTANCE_HEALTH"
echo "Sec. IPs: $SECONDARY_IPS"

python3 - <<PY
# Code Generated by Sidekick is for learning and experimentation purposes only.
import json
items = json.loads('''$EBS_DETAILS_JSON''')
if items:
    print("\nEBS DISK DETAILS")
    for d in items:
        print(f"Device Name={d['DeviceName']}; Volume ID={d['VolumeId']}; Type={d['Type']}; Size(GB)={d['SizeGB']}; IOPS={d['IOPS']}; Encrypted={d['Encrypted']}")
PY

python3 - <<PY
# Code Generated by Sidekick is for learning and experimentation purposes only.
import json
tags = json.loads('''$TAGS_JSON''')
if tags:
    print("\nINSTANCE TAGS")
    for t in sorted(tags, key=lambda x: x.get("Key","")):
        print(f"Tag Key={t.get('Key','')}; Tag Value={t.get('Value','')}")
PY

echo ""
echo "Running server-level validation through SSM..."

COMMAND_ID="$(aws ssm send-command \
  --region "$REGION" \
  --document-name "AWS-RunPowerShellScript" \
  --instance-ids "$INSTANCE_ID" \
  --parameters "$PARAMS_JSON" \
  --query "Command.CommandId" \
  --output text)"

echo "SSM Command ID: $COMMAND_ID"

aws ssm wait command-executed \
  --region "$REGION" \
  --command-id "$COMMAND_ID" \
  --instance-id "$INSTANCE_ID"

echo ""
echo "SERVER VALIDATION OUTPUT"
aws ssm get-command-invocation \
  --region "$REGION" \
  --command-id "$COMMAND_ID" \
  --instance-id "$INSTANCE_ID" \
  --query "StandardOutputContent" \
  --output text
